deploy:
  provider: pages
  skip_cleanup: true
  github_token: 5694dd9362da6ced053d6ed1bff756575c5bed5a # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
